version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/crowd-api
permissions:
  - object: /home/ec2-user/crowd-api
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: after-install.sh
      runas: root
