openapi: 3.1.0
x-stoplight:
  id: b8clt14el6lki
info:
  title: UNGUESS CORE
  description: Unguess core api
  contact:
    email: it@unguess.io
    name: Unguess
    url: 'https://unguess.io'
  version: '1.0'
  license:
    name: license
    url: 'https://unguess.io'
servers:
  - url: 'http://localhost:3000'
paths:
  /quests:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-quests
  /services:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-services
components:
  schemas:
    Service:
      title: Service
      x-stoplight:
        id: 2kt1wrskd9srq
      type: object
      properties:
        id:
          type: string
    Quest:
      title: Quest
      x-stoplight:
        id: 3nebbmk50z3k6
      type: object
      properties:
        id:
          type: string
        steps:
          oneOf:
            - $ref: '#/components/schemas/Step'
            - type: array
              items:
                $ref: '#/components/schemas/Step'
        access:
          type: array
          items:
            $ref: '#/components/schemas/AccessCondition'
    Step:
      title: Step
      x-stoplight:
        id: civvi8fyr15z4
      allOf:
        - type: object
          properties:
            id:
              type: string
            description:
              type: string
        - oneOf:
            - $ref: '#/components/schemas/BugFormStep'
            - $ref: '#/components/schemas/MediaStep'
            - $ref: '#/components/schemas/SurveyStep'
    AccessCondition:
      title: AccessCondition
      x-stoplight:
        id: h3tbhx96brqgb
      allOf:
        - type: object
          properties:
            id:
              type: string
        - oneOf:
            - $ref: '#/components/schemas/TimedAccessCondition'
            - $ref: '#/components/schemas/TesterListAccessCondition'
            - $ref: '#/components/schemas/TesterLimitAccessCondition'
            - $ref: '#/components/schemas/TesterDeviceOsVersionAccessCondition'
            - $ref: '#/components/schemas/TesterDeviceTypeAccessCondition'
            - $ref: '#/components/schemas/TesterDeviceOsAccessCondition'
    BugFormStep:
      title: BugFormStep
      x-stoplight:
        id: 8sgo1eehf94o0
      type: object
      properties:
        type:
          type: string
          enum:
            - bug
    SurveyStep:
      title: SurveyStep
      x-stoplight:
        id: n21983o003erp
      type: object
      properties:
        type:
          type: string
          enum:
            - survey
    MediaStep:
      title: MediaStep
      x-stoplight:
        id: 8094si4w0nj6e
      type: object
      properties:
        type:
          type: string
          enum:
            - media
    TimedAccessCondition:
      title: TimedAccessCondition
      x-stoplight:
        id: mdxonzt66170m
      type: object
      properties:
        endDate:
          type: string
        type:
          type: string
          enum:
            - timed
    TesterListAccessCondition:
      title: TesterListAccessCondition
      x-stoplight:
        id: rh1ncxf5whe5y
      type: object
      properties:
        list:
          type: array
          items:
            type: integer
        type:
          type: string
          enum:
            - testerlist
    TesterLimitAccessCondition:
      title: TesterLimitAccessCondition
      x-stoplight:
        id: i7cnb62aujjvk
      type: object
      properties:
        limit:
          type: number
        type:
          type: string
          enum:
            - testerlimit
    TesterDeviceOsAccessCondition:
      title: TesterDeviceOsAccessCondition
      x-stoplight:
        id: g7vye1s521ng0
      type: object
      properties:
        operatingSystem:
          type: string
        type:
          type: string
          enum:
            - testerDeviceOs
    TesterDeviceTypeAccessCondition:
      title: TesterDeviceTypeAccessCondition
      x-stoplight:
        id: g7vye1s521ng0
      type: object
      properties:
        deviceType:
          type: string
        type:
          type: string
          enum:
            - testerDeviceType
    TesterDeviceOsVersionAccessCondition:
      title: TesterDeviceOsVersionAccessCondition
      x-stoplight:
        id: g7vye1s521ng0
      type: object
      properties:
        operatingSystemVersion:
          type: string
        type:
          type: string
          enum:
            - testerDeviceOsVersion
