openapi: 3.1.0
x-stoplight:
  id: b8clt14el6lki
info:
  title: UNGUESS CORE
  description: Unguess core api
  contact:
    email: it@unguess.io
    name: Unguess
    url: 'https://unguess.io'
  version: '1.0'
  license:
    name: license
    url: 'https://unguess.io'
tags:
  - name: Quests
    description: The unit of work for the testers
  - name: Services
    description: The item bought from the customer
  - name: Templates
    description: A simple configuration used as a starting point
servers:
  - url: 'http://localhost:3000'
paths:
  /quests:
    get:
      summary: Get All Quests
      tags:
        - Quests
      responses:
        '200':
          description: OK
      operationId: get-quests
      description: 'Get all the quest available, regardless of the access conditions'
      security:
        - Key: []
  /services:
    get:
      summary: Get All Services
      tags:
        - Services
      responses:
        '200':
          description: OK
      operationId: get-services
      description: Get the services currently instantiated
      security:
        - Key: []
    post:
      summary: Instantiate a new service
      operationId: post-services
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  quests:
                    type: array
                    items:
                      allOf:
                        - type: object
                          properties:
                            id:
                              type: string
                        - $ref: '#/components/schemas/Quest'
      description: Create a new service from a template
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                templateId:
                  type: number
              required:
                - name
                - templateId
      security:
        - Key: []
  '/services/{id}/quests':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: The id of the service
    get:
      summary: Get the quests of a service
      tags:
        - Services
        - Quests
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                    - type: object
                      properties:
                        id:
                          type: string
                      required:
                        - id
                    - $ref: '#/components/schemas/Quest'
      operationId: get-services-id-quests
      description: Get the quest of an instance of service
    post:
      summary: Create a new quest in a service
      operationId: post-services-id-quests
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                    properties:
                      id:
                        type: string
                  - $ref: '#/components/schemas/Quest'
      description: Add a new quest to the instance of a service
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quest'
  '/services/{serviceId}/quests/{questId}':
    parameters:
      - schema:
          type: string
        name: serviceId
        in: path
        required: true
        description: The id of the service
      - schema:
          type: string
        name: questId
        in: path
        required: true
        description: The id of the quest
    post:
      summary: Push a new results to a quest
      operationId: post-services-serviceId-quests-questId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
      description: 'Allow an user to link something (a video, a bug, a survey result...) to a quest'
      security:
        - Key: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                author:
                  $ref: '#/components/schemas/Author'
                result:
                  $ref: ./Result/index.yaml#/components/schemas/Result
      tags:
        - Services
        - Quests
  /serviceTemplates:
    get:
      summary: Get All Templates
      tags:
        - Templates
      operationId: get-serviceTemplates
      description: Get all Service templates
      security:
        - Key: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                  required:
                    - id
                    - name
components:
  schemas:
    Quest:
      title: Quest
      x-stoplight:
        id: 3nebbmk50z3k6
      type: object
      properties:
        steps:
          oneOf:
            - $ref: '#/components/schemas/Step'
            - type: array
              items:
                $ref: '#/components/schemas/Step'
        access:
          type: array
          items:
            $ref: '#/components/schemas/AccessCondition'
    Step:
      title: Step
      x-stoplight:
        id: civvi8fyr15z4
      allOf:
        - type: object
          properties:
            id:
              type: string
            description:
              type: string
        - oneOf:
            - $ref: '#/components/schemas/BugFormStep'
            - $ref: '#/components/schemas/MediaStep'
            - $ref: '#/components/schemas/SurveyStep'
    AccessCondition:
      title: AccessCondition
      x-stoplight:
        id: h3tbhx96brqgb
      allOf:
        - type: object
          properties:
            id:
              type: string
        - oneOf:
            - $ref: '#/components/schemas/TimedAccessCondition'
            - $ref: '#/components/schemas/TesterListAccessCondition'
            - $ref: '#/components/schemas/TesterLimitAccessCondition'
            - $ref: '#/components/schemas/TesterDeviceOsVersionAccessCondition'
            - $ref: '#/components/schemas/TesterDeviceTypeAccessCondition'
            - $ref: '#/components/schemas/TesterDeviceOsAccessCondition'
    BugFormStep:
      title: BugFormStep
      x-stoplight:
        id: 8sgo1eehf94o0
      type: object
      properties:
        type:
          type: string
          enum:
            - bug
    SurveyStep:
      title: SurveyStep
      x-stoplight:
        id: n21983o003erp
      type: object
      properties:
        type:
          type: string
          enum:
            - survey
    MediaStep:
      title: MediaStep
      x-stoplight:
        id: 8094si4w0nj6e
      type: object
      properties:
        type:
          type: string
          enum:
            - media
    TimedAccessCondition:
      title: TimedAccessCondition
      x-stoplight:
        id: mdxonzt66170m
      type: object
      properties:
        endDate:
          type: string
        type:
          type: string
          enum:
            - timed
    TesterListAccessCondition:
      title: TesterListAccessCondition
      x-stoplight:
        id: rh1ncxf5whe5y
      type: object
      properties:
        list:
          type: array
          items:
            type: integer
        type:
          type: string
          enum:
            - testerlist
    TesterLimitAccessCondition:
      title: TesterLimitAccessCondition
      x-stoplight:
        id: i7cnb62aujjvk
      type: object
      properties:
        limit:
          type: number
        type:
          type: string
          enum:
            - testerlimit
    TesterDeviceOsAccessCondition:
      title: TesterDeviceOsAccessCondition
      x-stoplight:
        id: g7vye1s521ng0
      type: object
      properties:
        operatingSystem:
          type: string
        type:
          type: string
          enum:
            - testerDeviceOs
    TesterDeviceTypeAccessCondition:
      title: TesterDeviceTypeAccessCondition
      x-stoplight:
        id: g7vye1s521ng0
      type: object
      properties:
        deviceType:
          type: string
        type:
          type: string
          enum:
            - testerDeviceType
    TesterDeviceOsVersionAccessCondition:
      title: TesterDeviceOsVersionAccessCondition
      x-stoplight:
        id: g7vye1s521ng0
      type: object
      properties:
        operatingSystemVersion:
          type: string
        type:
          type: string
          enum:
            - testerDeviceOsVersion
    Result:
      title: Result
      x-stoplight:
        id: 08efaeqx7tcs5
      type: object
      properties:
        id:
          type: string
    Author:
      title: Author
      x-stoplight:
        id: 4xbbnpcg2a60y
      type: object
      properties:
        id:
          type: string
  securitySchemes:
    Key:
      name: API Key
      type: apiKey
      in: header
