/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/quests": {
    get: operations["get-quests"];
  };
  "/services": {
    /** Get the services currently instantiated */
    get: operations["get-services"];
    post: operations["post-services"];
  };
  "/services/{id}/quests": {
    get: operations["get-services-id-quests"];
    post: operations["post-services-id-quests"];
    parameters: {
      path: {
        id: string;
      };
    };
  };
  "/serviceTemplates": {
    /** Get all Service templates */
    get: operations["get-serviceTemplates"];
  };
}

export interface components {
  schemas: {
    /** Service */
    Service: {
      id?: string;
    };
    /** Quest */
    Quest: {
      steps?: components["schemas"]["Step"] | components["schemas"]["Step"][];
      access?: components["schemas"]["AccessCondition"][];
    };
    /** Step */
    Step: {
      id?: string;
      description?: string;
    } & (
      | components["schemas"]["BugFormStep"]
      | components["schemas"]["MediaStep"]
      | components["schemas"]["SurveyStep"]
    );
    /** AccessCondition */
    AccessCondition: {
      id?: string;
    } & (
      | components["schemas"]["TimedAccessCondition"]
      | components["schemas"]["TesterListAccessCondition"]
      | components["schemas"]["TesterLimitAccessCondition"]
      | components["schemas"]["TesterDeviceOsVersionAccessCondition"]
      | components["schemas"]["TesterDeviceTypeAccessCondition"]
      | components["schemas"]["TesterDeviceOsAccessCondition"]
    );
    /** BugFormStep */
    BugFormStep: {
      /** @enum {string} */
      type?: "bug";
    };
    /** SurveyStep */
    SurveyStep: {
      /** @enum {string} */
      type?: "survey";
    };
    /** MediaStep */
    MediaStep: {
      /** @enum {string} */
      type?: "media";
    };
    /** TimedAccessCondition */
    TimedAccessCondition: {
      endDate?: string;
      /** @enum {string} */
      type?: "timed";
    };
    /** TesterListAccessCondition */
    TesterListAccessCondition: {
      list?: number[];
      /** @enum {string} */
      type?: "testerlist";
    };
    /** TesterLimitAccessCondition */
    TesterLimitAccessCondition: {
      limit?: number;
      /** @enum {string} */
      type?: "testerlimit";
    };
    /** TesterDeviceOsAccessCondition */
    TesterDeviceOsAccessCondition: {
      operatingSystem?: string;
      /** @enum {string} */
      type?: "testerDeviceOs";
    };
    /** TesterDeviceTypeAccessCondition */
    TesterDeviceTypeAccessCondition: {
      deviceType?: string;
      /** @enum {string} */
      type?: "testerDeviceType";
    };
    /** TesterDeviceOsVersionAccessCondition */
    TesterDeviceOsVersionAccessCondition: {
      operatingSystemVersion?: string;
      /** @enum {string} */
      type?: "testerDeviceOsVersion";
    };
  };
}

export interface operations {
  "get-quests": {
    responses: {};
  };
  /** Get the services currently instantiated */
  "get-services": {
    responses: {};
  };
  "post-services": {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": {
            id?: string;
            name?: string;
            quests?: ({
              id?: string;
            } & components["schemas"]["Quest"])[];
          };
        };
      };
    };
    requestBody: {
      content: {
        "application/json": {
          name?: string;
          templateId?: number;
        };
      };
    };
  };
  "get-services-id-quests": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": ({
            id: string;
          } & components["schemas"]["Quest"])[];
        };
      };
    };
  };
  "post-services-id-quests": {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": {
            id?: string;
          } & components["schemas"]["Quest"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Quest"];
      };
    };
  };
  /** Get all Service templates */
  "get-serviceTemplates": {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": {
            id?: string;
            name?: string;
          }[];
        };
      };
    };
  };
}

export interface external {}
