openapi: 3.1.0
x-stoplight:
  id: b8clt14el6lki
info:
  title: Steps Schemas
  description: Unguess core api
  contact:
    email: it@unguess.io
    name: Unguess
    url: 'https://unguess.io'
  version: '1.0'
  license:
    name: license
    url: 'https://unguess.io'
tags:
  - name: Quests
    description: The unit of work for the testers
  - name: Services
    description: The item bought from the customer
  - name: Templates
    description: A simple configuration used as a starting point
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    Step:
      title: Step
      x-stoplight:
        id: civvi8fyr15z4
      allOf:
        - type: object
          properties:
            id:
              type: number
            description:
              type: string
        - oneOf:
            - $ref: '#/components/schemas/BugFormStep'
            - $ref: '#/components/schemas/MediaStep'
            - $ref: '#/components/schemas/SurveyStep'
    BugFormStep:
      title: BugFormStep
      x-stoplight:
        id: 8sgo1eehf94o0
      type: object
      properties:
        type:
          type: string
          enum:
            - bug
    SurveyStep:
      title: SurveyStep
      x-stoplight:
        id: n21983o003erp
      type: object
      properties:
        type:
          type: string
          enum:
            - survey
    MediaStep:
      title: MediaStep
      x-stoplight:
        id: 8094si4w0nj6e
      type: object
      properties:
        type:
          type: string
          enum:
            - media
  securitySchemes:
    Key:
      name: API Key
      type: apiKey
      in: header
